### ISSUE TITLE
Installation issues - non-standard C compiler?

### ISSUE THREAD

**Issue by lukeholman** [jobovy/extreme-deconvolution#18]
Hi there,

I am using a normal Mac, and cannot install. Based on the errors I get, it seems like the make file uses an option (-fopenmp) that is not available for the default Mac compiler (clang), so I get errors like:

clang: error: unsupported option '-fopenmp'

Could you maybe edit the installation help to explain how to fix this, for mere mortals using the default C++ compilers? I think I need to install a new C compiler, like llvm, and then force my system to use that instead of the default clang one by editing the Makevars file. I had a good crack at this, but it isn't trivially easy, at least for people like me that know R but not much else.

Many thanks!

Luke

**Comment by lukeholman** [comment]
I noticed that the README mentions this a little, so I tried to follow the instructions. Are you saying I need to enter something like:

    ifeq ($(CC),)
      CC=/usr/local/opt/llvm/bin/clang
    endif

And also edit the ~/.R/Makevars, like:

    CC=/usr/local/opt/llvm/bin/clang
    CXX=/usr/local/opt/llvm/bin/clang++

**Comment by lukeholman** [comment]
Alright, so that actually does work, sort of, if I check for typos.

However, now I get a new problem. When typing `make rpackage`, I get for following in `install.out`. I have installed GSL, but perhaps I need to edit the Makefile to say where it is (it's in the standard place that GSL installs to when following the instructions)?

```
* installing *source* package ‘ExtremeDeconvolution’ ...
** libs
** arch -
/usr/local/opt/llvm/bin/clang       -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp -c bovy_det.c bovy_randvec.c calc_splitnmerge.c cleanup.c log$
bovy_randvec.c:19:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
1 error generated.
calc_splitnmerge.c:29:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
1 error generated.
logsum.c:21:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
logsum.c:37:22: warning: explicitly assigning value of variable of type 'double' to itself [-Wself-assign]
  (min >  max) ? (max=max) : (max=min);
                  ~~~^~~~
1 warning and 1 error generated.
minmax.c:21:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
1 error generated.
normalize_row.c:24:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
1 error generated.
parse_option.c:17:10: error: 'proj_gauss_main.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_main.h>
         ^~~~~~~~~~~~~~~~~~~
         "proj_gauss_main.h"
In file included from parse_option.c:17:
./proj_gauss_main.h:6:10: error: 'proj_gauss_mixtures.h' file not found with <angled> include; use "quotes" instead
#include <proj_gauss_mixtures.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
         "proj_gauss_mixtures.h"
```

**Comment by jobovy** [comment]
Hi,

With regards to the OpenMP issue, see [this section](https://github.com/jobovy/extreme-deconvolution#installation-faq) of the README.

To change the compiler, you should be able to define the environment variables
```
export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++
```
without having to edit the ``Makefile`` (but editing the ``Makefile`` should work fine too).

I'm not sure what's going on in your latest issue, the code seems to not be able to find the files included with the package. Please post full input and output, using [pastebin](https://pastebin.com/) for long in/outputs, including which directory you're in.

**Comment by lukeholman** [comment]
Hi there, thanks so much!

So in the following pastebin of my Terminal, I re-installed e-d with `git clone`, `cd` into the directory, then type `make`: https://pastebin.com/UeePnj3q. I did that after pasting in the two export commands you mentioned. Maybe I need to somehow link it to the GSL installation? 

Cheers!

**Comment by lukeholman** [comment]
Thanks so much! 

So, I deleted all the references to OpenMP in both make files as suggested, and I have got the main `make` call to run fine, and the `make rpackage` call also works. However now the R package won't install. Typing `sudo R CMD INSTALL ExtremeDeconvolution_1.3.tar.gz` (with or without sudo) gives the following, suggesting that it cannot find all the files that are in r/src/ for some reason, or perhaps that the angled brackets need to be replaced with quotes somewhere? Note that the compiler is still using the -fopenmp option even though I deleted it in the make file, although I have managed to get R to use the llvm compiler so it works - possibly relevant? Link: https://pastebin.com/tBD123rk

**Comment by jobovy** [comment]
Sorry for the delay, but I'm quite puzzled about what is going on here. I never use R, so maybe I just don't understand enough about how the R installer compiles and installs code (perhaps @gaow or @pcarbo can take a peek at this issue, since they've both worked on the R interface).

What's puzzling is that the code clearly can compile on your system, because you can run ``make`` and ``make rpackage`` (in the first line of your last error message you erroneously did ``make r package`` leading to an error, but I assume ``make rpackage`` has worked before?). But the compilation done by the R install command then does something different that causes it to fail. From looking at the compilation, it seems like the R compilation is using the wrong compilation flags, they seem to be:
```
-O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp -O3 -Wall -pipe -pedantic -std=gnu99 -fopenmp
```
while they should be something like
```
-std=c99 -fPIC -fopenmp -shared -I. -Isrc
```
I suspect that the absence of ``-I. -Isrc`` in particular might be to blame for the actual error message that you are getting (because those options specify where to look for the ``.h`` files that the compiler is complaining about).

What I don't know is why those wrong options are used. Seems like R can use compilation parameters specified in a file ``~/.R/Makevars``, do you have such a file with strange settings?

Maybe the following would work: Start with a clean new version of this repository, define your ``CC`` etc variables again if necessary:
```
export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++
```
In the top-level Makefile, add a line below [this line](https://github.com/jobovy/extreme-deconvolution/blob/master/Makefile#L128) that does
```
cp src/*.o r/src
```
and remove the next line (starting with ``patch``). In the ``r/src/Makefile`` file remove [this line](https://github.com/jobovy/extreme-deconvolution/blob/master/r/src/Makefile#L9). Then do
```
patch src/proj_gauss_mixtures_IDL.c < r/src/proj_gauss_mixtures_R.patch
make
make rpackage
R CMD INSTALL ExtremeDeconvolution_1.3.tar.gz
```
The hope is that this way the code gets compiled by ``make``, the compiled objects get transfered to the ``ExtremeDeconvolution_1.3.tar.gz`` file and they don't get compiled by ``R`` anymore, avoiding the error that you have been getting...

**Comment by lukeholman** [comment]
Hi there, thanks so much for your patience and help! The issue is that in my earlier Googling, I had found an example `~/.R/Makevars` file that supposedly allows for compilation using OpenMP. It has a number of lines after those two calls `export` you mention, which I didn't fully understand, but they simply looked like they were telling R to use OpenMP when needed. I deleted the extra lines, leaving just the `export` ones, and the R package installed fine! 

Sorry for not making more progress with this on my own - with hindsight, you did provide pretty clear instructions, it just wasn't clear because I read the first few lines and then assumed I had it covered, and I haven't had to tinker with compilers before.  In case you're curious I am installing your package because I'd like to use the R package `mashr`, which depends on it (I'm hoping to do some GWAS and gene expression stuff, not physics!). Pretty neat how diverse the applications of your package are! Thanks again for your help.

**Comment by pcarbo** [comment]
@lukeholman I happened to notice your note about `mashr`---we (the mashr authors) would be interested to find out if you make much progress using mashr, and if you encounter any difficulties in using it.

Also, @lukeholman @jobovy you may be interested in [my tips for installing R packages from source on Mac](https://pcarbo.github.io/pcarbo/r-macos.html).

**Comment by jobovy** [comment]
@lukeholman -- Okay, glad that it is now sorted out! Glad to hear that this code is useful for stuff other than physics/astrophysics!

@pcarbo -- Thanks, those instructions seem very useful, maybe I'll add a link to them in the README.
