### ISSUE TITLE
logL descreases when fitting with big data

### ISSUE THREAD

**Issue by philastrophist** [jobovy/extreme-deconvolution#28]
When using more than 15 components to ~600,000 data points, extreme deconvolution seems to give the wrong answer. I.e. the logL decreases after some number of iterations (actually much sooner than expected).

```
Warning: log likelihood decreased by -1.033e-08
```

I have a minimal 1D example here:

```
from extreme_deconvolution import extreme_deconvolution as bovyXD
from sklearn.mixture import GaussianMixture as skl_GMM
from scipy import stats
import numpy as np

arrs = np.load('data.npz')
X, Xerr = arrs['X'], arrs['Xerr']

n_components = 28
w = 0.001
gmm = skl_GMM(n_components, max_iter=1, reg_covar=w, covariance_type='full').fit(X, Xerr)  # dirty initialisation
logl = bovyXD(X, Xerr, gmm.weights_, gmm.means_, gmm.covariances_, tol=1e-7, w=w)
```

and I've attached the data as a numpy file (to be unzipped).

Is this a problem with numerical precision? And is there anyway round it?

Thanks

[data.zip](https://github.com/jobovy/extreme-deconvolution/files/6823438/data.zip)

**Comment by jobovy** [comment]
Hi! Yes, this is known behavior that just results from small numerical errors, that's why the decrease is so small. This typically means that the algorithm has converged so the changes in log likelihood are ~0. Do you think the algorithm hasn't converged in your case? I've run XD many times and had this happen a lot, but the resulting fit was always good...

**Comment by philastrophist** [comment]
I became suspicious when I plotted BIC and AIC with the number of components. 
They both increase (slowly) with the number of components up until 15/16 and then they both crash down again (this is accompanied by the message about logL decreasing. 
So I don't think it can be giving a good fit. I'll see if I can get the plot to show you

**Comment by philastrophist** [comment]
OK, I've just ran it again and it seems like I was mistaken on the AIC/BIC. But the time taken at >17 components is much shorter than ~14.

**Comment by jobovy** [comment]
If you're using random initialization, it could be that a different initial condition leads to slightly different behavior. And trying some different random initialization for a given K is generally a good idea.

There isn't much to do about this issue, because it's very difficult to control the random errors in such a way that they wouldn't ever decrease the likelihood (I don't think this is possible). The only option would be to add an option to disregard a decreasing likelihood and just iterate until you reach `maxiter` so you can force the algorithm to optimize for a given number of iterations.

**Comment by philastrophist** [comment]
That makes sense. I reimplemented the XD algorithm quickly to see what would happen if we ignore the -logL. It seems to continue to move away from that coordinate and back or onto another. So I guess it's just nudging it. 

I guess if I were to perform XD with data batches, then this schocastic behaviour would be more obvious
